namespace MaterialDesignThemes.Wpf
{
    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    /// <summary>
    /// List of available icons for use with <see cref="PackIcon" />.
    /// </summary>
    /// <remarks>
    /// All icons sourced from Material Design Icons Font - https://materialdesignicons.com/ - in accordance of 
    /// https://github.com/Templarian/MaterialDesign/blob/master/LICENSE.
    /// </remarks>
    public enum PackIconKind
    {
        AutoGenerated,
        DoNotAmend
    }
}

