namespace MaterialDesignThemes.Wpf
{
    /// <summary>
    /// List of available icons for use with <see cref="Icon"/>.
    /// </summary>
    /// <remarks>
    /// All icons sourced from Material Design Icons Font - https://materialdesignicons.com/ - in accordance of 
    /// https://github.com/Templarian/MaterialDesign/blob/master/LICENSE.
    /// </remarks>
    public enum IconType
    {
        AutoGeneratedDoNotAmend
    }
}