//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by msresgen.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
namespace MaterialDesignThemes.Wpf;
static partial class ResourceDictionaryExtensions
{
    private static partial void LoadThemeColors(ResourceDictionary resourceDictionary, Theme theme)
    {
        theme.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.Background", "MaterialDesignPaper");
        theme.Foreground = GetColor(resourceDictionary, "MaterialDesign.Brush.Foreground", "MaterialDesignBody");
        theme.ForegroundLight = GetColor(resourceDictionary, "MaterialDesign.Brush.ForegroundLight", "MaterialDesignBodyLight", "MaterialDesignCheckBoxOff", "MaterialDesignTextBoxBorder");
        theme.ValidationError = GetColor(resourceDictionary, "MaterialDesign.Brush.ValidationError", "MaterialDesignValidationErrorBrush");
        theme.Buttons.FlatClick = GetColor(resourceDictionary, "MaterialDesign.Brush.Button.FlatClick", "MaterialDesignFlatButtonClick");
        theme.Buttons.Ripple = GetColor(resourceDictionary, "MaterialDesign.Brush.Button.Ripple", "MaterialDesignFlatButtonRipple", "MaterialDesignSnackbarRipple");
        theme.Buttons.FlatRipple = GetColor(resourceDictionary, "MaterialDesign.Brush.Button.FlatRipple", "MaterialDesignFlatButtonRipple", "MaterialDesignSnackbarRipple");
        theme.SnackBars.Ripple = GetColor(resourceDictionary, "MaterialDesign.Brush.SnackBar.Ripple", "MaterialDesignFlatButtonRipple", "MaterialDesignSnackbarRipple");
        theme.SnackBars.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.SnackBar.Background", "MaterialDesignSnackbarBackground");
        theme.SnackBars.MouseOver = GetColor(resourceDictionary, "MaterialDesign.Brush.SnackBar.MouseOver", "MaterialDesignSnackbarMouseOver");
        theme.Cards.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.Card.Background", "MaterialDesignBackground", "MaterialDesignCardBackground");
        theme.CheckBoxes.Disabled = GetColor(resourceDictionary, "MaterialDesign.Brush.CheckBox.Disabled", "MaterialDesignCheckBoxDisabled");
        theme.CheckBoxes.Off = GetColor(resourceDictionary, "MaterialDesign.Brush.CheckBox.Off", "MaterialDesignBodyLight", "MaterialDesignCheckBoxOff", "MaterialDesignTextBoxBorder");
        theme.Chips.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.Chip.Background", "MaterialDesignChipBackground");
        theme.DataGrids.ButtonPressed = GetColor(resourceDictionary, "MaterialDesign.Brush.DataGrid.ButtonPressed");
        theme.DataGrids.ComboBoxSelected = GetColor(resourceDictionary, "MaterialDesign.Brush.DataGrid.ComboBoxSelected");
        theme.DataGrids.RowHoverBackground = GetColor(resourceDictionary, "MaterialDesign.Brush.DataGrid.RowHoverBackground", "MaterialDesignDataGridRowHoverBackground");
        theme.DataGrids.Selected = GetColor(resourceDictionary, "MaterialDesign.Brush.DataGrid.Selected");
        theme.DataGrids.ColumnHeaderForeground = GetColor(resourceDictionary, "MaterialDesign.Brush.DataGrid.ColumnHeaderForeground", "MaterialDesignColumnHeader", "MaterialDesignTextAreaBorder");
        theme.TextBoxes.Border = GetColor(resourceDictionary, "MaterialDesign.Brush.TextBox.Border", "MaterialDesignBodyLight", "MaterialDesignCheckBoxOff", "MaterialDesignTextBoxBorder");
        theme.TextBoxes.OutlineBorder = GetColor(resourceDictionary, "MaterialDesign.Brush.TextBox.OutlineBorder", "MaterialDesignColumnHeader", "MaterialDesignTextAreaBorder");
        theme.TextBoxes.DisabledBackground = GetColor(resourceDictionary, "MaterialDesign.Brush.TextBox.DisabledBackground", "MaterialDesignTextFieldBoxDisabledBackground");
        theme.TextBoxes.FilledBackground = GetColor(resourceDictionary, "MaterialDesign.Brush.TextBox.FilledBackground", "MaterialDesignTextFieldBoxBackground");
        theme.TextBoxes.HoverBackground = GetColor(resourceDictionary, "MaterialDesign.Brush.TextBox.HoverBackground", "MaterialDesignTextFieldBoxHoverBackground", "MaterialDesignDivider");
        theme.TextBoxes.OutlineInactiveBorder = GetColor(resourceDictionary, "MaterialDesign.Brush.TextBox.OutlineInactiveBorder", "MaterialDesignTextAreaInactiveBorder");
        theme.GridSplitters.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.GridSplitter.Background");
        theme.Headers.Foreground = GetColor(resourceDictionary, "MaterialDesign.Brush.Header.Foreground", "MaterialDesignColumnHeader", "MaterialDesignTextAreaBorder");
        theme.ListViews.Selected = GetColor(resourceDictionary, "MaterialDesign.Brush.ListView.Selected");
        theme.ScrollBars.Foreground = GetColor(resourceDictionary, "MaterialDesign.Brush.ScrollBar.Foreground");
        theme.ScrollBars.RepeatButtonBackground = GetColor(resourceDictionary, "MaterialDesign.Brush.ScrollBar.RepeatButtonBackground");
        theme.Separators.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.Separator.Background");
        theme.ToolBars.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.ToolBar.Background", "MaterialDesignToolBarBackground");
        theme.ToolBars.Items.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.ToolBar.Item.Background", "MaterialDesignToolBackground");
        theme.ToolBars.Items.Foreground = GetColor(resourceDictionary, "MaterialDesign.Brush.ToolBar.Item.Foreground", "MaterialDesignToolForeground");
        theme.ToolTips.Background = GetColor(resourceDictionary, "MaterialDesign.Brush.ToolTip.Background", "MaterialDesignToolTipBackground");
    }

    private static partial void ApplyThemeColors(ResourceDictionary resourceDictionary, Theme theme)
    {
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Background", theme.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignPaper", theme.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Foreground", theme.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignBody", theme.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ForegroundLight", theme.ForegroundLight);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignBodyLight", theme.ForegroundLight);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignCheckBoxOff", theme.ForegroundLight);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextBoxBorder", theme.ForegroundLight);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ValidationError", theme.ValidationError);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignValidationErrorBrush", theme.ValidationError);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Button.FlatClick", theme.Buttons.FlatClick);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignFlatButtonClick", theme.Buttons.FlatClick);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Button.Ripple", theme.Buttons.Ripple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignFlatButtonRipple", theme.Buttons.Ripple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignSnackbarRipple", theme.Buttons.Ripple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Button.FlatRipple", theme.Buttons.FlatRipple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignFlatButtonRipple", theme.Buttons.FlatRipple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignSnackbarRipple", theme.Buttons.FlatRipple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.SnackBar.Ripple", theme.SnackBars.Ripple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignFlatButtonRipple", theme.SnackBars.Ripple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignSnackbarRipple", theme.SnackBars.Ripple);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.SnackBar.Background", theme.SnackBars.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignSnackbarBackground", theme.SnackBars.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.SnackBar.MouseOver", theme.SnackBars.MouseOver);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignSnackbarMouseOver", theme.SnackBars.MouseOver);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Card.Background", theme.Cards.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignBackground", theme.Cards.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignCardBackground", theme.Cards.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.CheckBox.Disabled", theme.CheckBoxes.Disabled);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignCheckBoxDisabled", theme.CheckBoxes.Disabled);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.CheckBox.Off", theme.CheckBoxes.Off);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignBodyLight", theme.CheckBoxes.Off);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignCheckBoxOff", theme.CheckBoxes.Off);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextBoxBorder", theme.CheckBoxes.Off);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Chip.Background", theme.Chips.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignChipBackground", theme.Chips.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.DataGrid.ButtonPressed", theme.DataGrids.ButtonPressed);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.DataGrid.ComboBoxSelected", theme.DataGrids.ComboBoxSelected);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.DataGrid.RowHoverBackground", theme.DataGrids.RowHoverBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignDataGridRowHoverBackground", theme.DataGrids.RowHoverBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.DataGrid.Selected", theme.DataGrids.Selected);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.DataGrid.ColumnHeaderForeground", theme.DataGrids.ColumnHeaderForeground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignColumnHeader", theme.DataGrids.ColumnHeaderForeground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextAreaBorder", theme.DataGrids.ColumnHeaderForeground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.TextBox.Border", theme.TextBoxes.Border);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignBodyLight", theme.TextBoxes.Border);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignCheckBoxOff", theme.TextBoxes.Border);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextBoxBorder", theme.TextBoxes.Border);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.TextBox.OutlineBorder", theme.TextBoxes.OutlineBorder);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignColumnHeader", theme.TextBoxes.OutlineBorder);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextAreaBorder", theme.TextBoxes.OutlineBorder);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.TextBox.DisabledBackground", theme.TextBoxes.DisabledBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextFieldBoxDisabledBackground", theme.TextBoxes.DisabledBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.TextBox.FilledBackground", theme.TextBoxes.FilledBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextFieldBoxBackground", theme.TextBoxes.FilledBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.TextBox.HoverBackground", theme.TextBoxes.HoverBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextFieldBoxHoverBackground", theme.TextBoxes.HoverBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignDivider", theme.TextBoxes.HoverBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.TextBox.OutlineInactiveBorder", theme.TextBoxes.OutlineInactiveBorder);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextAreaInactiveBorder", theme.TextBoxes.OutlineInactiveBorder);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.GridSplitter.Background", theme.GridSplitters.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Header.Foreground", theme.Headers.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignColumnHeader", theme.Headers.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignTextAreaBorder", theme.Headers.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ListView.Selected", theme.ListViews.Selected);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ScrollBar.Foreground", theme.ScrollBars.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ScrollBar.RepeatButtonBackground", theme.ScrollBars.RepeatButtonBackground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.Separator.Background", theme.Separators.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ToolBar.Background", theme.ToolBars.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignToolBarBackground", theme.ToolBars.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ToolBar.Item.Background", theme.ToolBars.Items.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignToolBackground", theme.ToolBars.Items.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ToolBar.Item.Foreground", theme.ToolBars.Items.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignToolForeground", theme.ToolBars.Items.Foreground);
        SetSolidColorBrush(resourceDictionary, "MaterialDesign.Brush.ToolTip.Background", theme.ToolTips.Background);
        SetSolidColorBrush(resourceDictionary, "MaterialDesignToolTipBackground", theme.ToolTips.Background);
    }
}
