//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by msresgen.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System.Windows.Media;

using MaterialDesignThemes.Wpf.Themes.Internal;

namespace MaterialDesignThemes.Wpf;

static partial class ThemeExtensions
{
    public static partial void SetLightTheme(this Theme theme)
    {
        theme.Background = BaseThemeColors.Neutral900;
        theme.Foreground = BaseThemeColors.Black900;
        theme.ForegroundLight = BaseThemeColors.Black500;
        theme.ValidationError = Color.FromArgb(0xFF, 0xB0, 0x00, 0x20);
        theme.Buttons.FlatClick = BaseThemeColors.Neutral800;
        theme.Buttons.Ripple = BaseThemeColors.Neutral700;
        theme.Buttons.FlatRipple = BaseThemeColors.Neutral700;
        theme.SnackBars.Ripple = BaseThemeColors.Neutral700;
        theme.SnackBars.Background = BaseThemeColors.Neutral100;
        theme.SnackBars.MouseOver = BaseThemeColors.Neutral200;
        theme.Cards.Background = BaseThemeColors.White1000;
        theme.CheckBoxes.Disabled = BaseThemeColors.Neutral700;
        theme.CheckBoxes.Off = BaseThemeColors.Black500;
        theme.Chips.Background = Color.FromArgb(0x12, 0x00, 0x00, 0x00);
        theme.DataGrids.ButtonPressed = BaseThemeColors.Neutral800;
        theme.DataGrids.ComboBoxSelected = BaseThemeColors.Neutral800;
        theme.DataGrids.RowHoverBackground = BaseThemeColors.Black50;
        theme.DataGrids.Selected = BaseThemeColors.Neutral800;
        theme.DataGrids.ColumnHeaderForeground = BaseThemeColors.Black700;
        theme.TextBoxes.Border = BaseThemeColors.Black500;
        theme.TextBoxes.OutlineBorder = BaseThemeColors.Black700;
        theme.TextBoxes.DisabledBackground = BaseThemeColors.Black50;
        theme.TextBoxes.FilledBackground = BaseThemeColors.Black50;
        theme.TextBoxes.HoverBackground = BaseThemeColors.Black100;
        theme.TextBoxes.OutlineInactiveBorder = BaseThemeColors.Black200;
        theme.GridSplitters.Background = BaseThemeColors.Neutral800;
        theme.Headers.Foreground = BaseThemeColors.Black700;
        theme.ListViews.Selected = BaseThemeColors.Neutral800;
        theme.ScrollBars.Foreground = BaseThemeColors.Neutral800;
        theme.ScrollBars.RepeatButtonBackground = BaseThemeColors.Neutral800;
        theme.Separators.Background = BaseThemeColors.Neutral800;
        theme.ToolBars.Background = BaseThemeColors.Neutral900;
        theme.ToolBars.Items.Background = BaseThemeColors.Neutral800;
        theme.ToolBars.Items.Foreground = BaseThemeColors.Neutral300;
        theme.ToolTips.Background = BaseThemeColors.Neutral400;
    }

    public static partial void SetDarkTheme(this Theme theme)
    {
        theme.Background = BaseThemeColors.Neutral100;
        theme.Foreground = BaseThemeColors.White900;
        theme.ForegroundLight = BaseThemeColors.White500;
        theme.ValidationError = Color.FromArgb(0xFF, 0xCF, 0x66, 0x79);
        theme.Buttons.FlatClick = Color.FromArgb(0x19, 0x75, 0x75, 0x75);
        theme.Buttons.Ripple = BaseThemeColors.Neutral700;
        theme.Buttons.FlatRipple = BaseThemeColors.Neutral700;
        theme.SnackBars.Ripple = BaseThemeColors.Neutral700;
        theme.SnackBars.Background = BaseThemeColors.Neutral800;
        theme.SnackBars.MouseOver = BaseThemeColors.Neutral700;
        theme.Cards.Background = BaseThemeColors.Neutral200;
        theme.CheckBoxes.Disabled = BaseThemeColors.Neutral300;
        theme.CheckBoxes.Off = BaseThemeColors.White500;
        theme.Chips.Background = Color.FromArgb(0xFF, 0x2E, 0x3C, 0x43);
        theme.DataGrids.ButtonPressed = BaseThemeColors.Neutral400;
        theme.DataGrids.ComboBoxSelected = BaseThemeColors.Neutral400;
        theme.DataGrids.RowHoverBackground = BaseThemeColors.White100;
        theme.DataGrids.Selected = BaseThemeColors.Neutral400;
        theme.DataGrids.ColumnHeaderForeground = BaseThemeColors.White700;
        theme.TextBoxes.Border = BaseThemeColors.White500;
        theme.TextBoxes.OutlineBorder = BaseThemeColors.White700;
        theme.TextBoxes.DisabledBackground = BaseThemeColors.White50;
        theme.TextBoxes.FilledBackground = BaseThemeColors.White100;
        theme.TextBoxes.HoverBackground = BaseThemeColors.White100;
        theme.TextBoxes.OutlineInactiveBorder = BaseThemeColors.White200;
        theme.GridSplitters.Background = BaseThemeColors.Neutral400;
        theme.Headers.Foreground = BaseThemeColors.White700;
        theme.ListViews.Selected = BaseThemeColors.Neutral400;
        theme.ScrollBars.Foreground = BaseThemeColors.Neutral400;
        theme.ScrollBars.RepeatButtonBackground = BaseThemeColors.Neutral400;
        theme.Separators.Background = BaseThemeColors.Neutral400;
        theme.ToolBars.Background = BaseThemeColors.Neutral50;
        theme.ToolBars.Items.Background = BaseThemeColors.Neutral800;
        theme.ToolBars.Items.Foreground = BaseThemeColors.Neutral300;
        theme.ToolTips.Background = BaseThemeColors.Neutral900;
    }
}
