//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by mdresgen.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
using System.Windows.Media;

using MaterialDesignThemes.Wpf.Themes.Internal;

namespace MaterialDesignThemes.Wpf;

static partial class ThemeExtensions
{
    public static partial void SetLightTheme(this Theme theme)
    {
        theme.Background = BaseThemeColors.Neutral900;
        theme.Foreground = BaseThemeColors.Black900;
        theme.ForegroundLight = BaseThemeColors.Black500;
        theme.ValidationError = Color.FromArgb(0xFF, 0xB0, 0x00, 0x20);
        theme.Badgeds.DarkBackground = BaseThemeColors.Neutral100;
        theme.Badgeds.DarkForeground = BaseThemeColors.Neutral900;
        theme.Badgeds.LightBackground = BaseThemeColors.Neutral900;
        theme.Badgeds.LightForeground = BaseThemeColors.Black900;
        theme.Buttons.FlatClick = BaseThemeColors.Neutral800;
        theme.Buttons.Ripple = BaseThemeColors.Neutral700;
        theme.Buttons.FlatRipple = BaseThemeColors.Neutral700;
        theme.SnackBars.Ripple = BaseThemeColors.Neutral700;
        theme.SnackBars.Background = BaseThemeColors.Neutral100;
        theme.SnackBars.MouseOver = BaseThemeColors.Neutral200;
        theme.Cards.Background = BaseThemeColors.White1000;
        theme.Cards.Border = BaseThemeColors.Neutral700;
        theme.CheckBoxes.Disabled = BaseThemeColors.Neutral700;
        theme.CheckBoxes.UncheckedBorder = BaseThemeColors.Black100;
        theme.CheckBoxes.Off = BaseThemeColors.Black500;
        theme.Chips.Background = Color.FromArgb(0x12, 0x00, 0x00, 0x00);
        theme.Chips.OutlineBorder = BaseThemeColors.Black100;
        theme.ColorZones.DarkBackground = BaseThemeColors.Neutral100;
        theme.ColorZones.DarkForeground = BaseThemeColors.Neutral900;
        theme.ColorZones.LightBackground = BaseThemeColors.Neutral900;
        theme.ColorZones.LightForeground = BaseThemeColors.Black900;
        theme.ComboBoxes.Disabled = BaseThemeColors.Neutral700;
        theme.ComboBoxes.FilledBackground = BaseThemeColors.Black50;
        theme.ComboBoxes.HoverBackground = BaseThemeColors.Black100;
        theme.ComboBoxes.OutlineInactiveBorder = BaseThemeColors.Black200;
        theme.ComboBoxes.HoverBorder = BaseThemeColors.Black900;
        theme.ComboBoxes.Border = BaseThemeColors.Black500;
        theme.ComboBoxes.OutlineBorder = BaseThemeColors.Black700;
        theme.ComboBoxes.Popups.DarkBackground = BaseThemeColors.Neutral100;
        theme.ComboBoxes.Popups.DarkForeground = BaseThemeColors.Neutral900;
        theme.ComboBoxes.Popups.LightBackground = BaseThemeColors.Neutral900;
        theme.ComboBoxes.Popups.LightForeground = BaseThemeColors.Black900;
        theme.DataGrids.Border = BaseThemeColors.Black100;
        theme.DataGrids.ButtonPressed = BaseThemeColors.Neutral800;
        theme.DataGrids.ComboBoxHover = BaseThemeColors.Black100;
        theme.DataGrids.ComboBoxSelected = BaseThemeColors.Neutral800;
        theme.DataGrids.PopupBorder = BaseThemeColors.Black100;
        theme.DataGrids.RowHoverBackground = BaseThemeColors.Black50;
        theme.DataGrids.Selected = BaseThemeColors.Neutral800;
        theme.DataGrids.ColumnHeaderForeground = BaseThemeColors.Black700;
        theme.TextBoxes.HoverBorder = BaseThemeColors.Black900;
        theme.TextBoxes.Border = BaseThemeColors.Black500;
        theme.TextBoxes.OutlineBorder = BaseThemeColors.Black700;
        theme.TextBoxes.DisabledBackground = BaseThemeColors.Black50;
        theme.TextBoxes.FilledBackground = BaseThemeColors.Black50;
        theme.TextBoxes.HoverBackground = BaseThemeColors.Black100;
        theme.TextBoxes.OutlineInactiveBorder = BaseThemeColors.Black200;
        theme.PasswordBoxes.HoverBorder = BaseThemeColors.Black900;
        theme.PasswordBoxes.Border = BaseThemeColors.Black500;
        theme.PasswordBoxes.OutlineBorder = BaseThemeColors.Black700;
        theme.PasswordBoxes.FilledBackground = BaseThemeColors.Black50;
        theme.PasswordBoxes.HoverBackground = BaseThemeColors.Black100;
        theme.PasswordBoxes.OutlineInactiveBorder = BaseThemeColors.Black200;
        theme.GridSplitters.Background = BaseThemeColors.Black100;
        theme.GridSplitters.PreviewBackground = BaseThemeColors.Neutral800;
        theme.Headers.Foreground = BaseThemeColors.Black700;
        theme.ListBoxItems.Border = BaseThemeColors.Black100;
        theme.ListBoxItems.Selected = BaseThemeColors.Black100;
        theme.ListViews.Hover = BaseThemeColors.Black100;
        theme.ListViews.Selected = BaseThemeColors.Neutral800;
        theme.ListViews.Separator = BaseThemeColors.Black100;
        theme.RadioButtons.Border = BaseThemeColors.Black100;
        theme.RadioButtons.Checked = BaseThemeColors.Black100;
        theme.RadioButtons.Disabled = BaseThemeColors.Neutral700;
        theme.RadioButtons.Outline = BaseThemeColors.Black500;
        theme.RadioButtons.Chips.CheckedBackground = BaseThemeColors.Black100;
        theme.ScrollBars.ActiveBackground = BaseThemeColors.Black100;
        theme.ScrollBars.Foreground = BaseThemeColors.Neutral800;
        theme.ScrollBars.RepeatButtonBackground = BaseThemeColors.Neutral800;
        theme.Separators.Background = BaseThemeColors.Neutral800;
        theme.TabControls.Divider = BaseThemeColors.Black100;
        theme.ToolBars.Background = BaseThemeColors.Neutral900;
        theme.ToolBars.Separator = BaseThemeColors.Black100;
        theme.ToolBars.Thumbs.Foreground = BaseThemeColors.Black100;
        theme.ToolBars.Items.Background = BaseThemeColors.Neutral800;
        theme.ToolBars.Items.Foreground = BaseThemeColors.Neutral300;
        theme.ToolBars.Overflows.Border = BaseThemeColors.Black100;
        theme.ToggleButtons.Background = BaseThemeColors.Neutral800;
        theme.ToggleButtons.Foreground = BaseThemeColors.Neutral300;
        theme.ToggleButtons.Switches.TrackOffBackground = BaseThemeColors.White1000;
        theme.ToolTips.Background = BaseThemeColors.Neutral400;
    }

    public static partial void SetDarkTheme(this Theme theme)
    {
        theme.Background = BaseThemeColors.Neutral100;
        theme.Foreground = BaseThemeColors.White900;
        theme.ForegroundLight = BaseThemeColors.White500;
        theme.ValidationError = Color.FromArgb(0xFF, 0xCF, 0x66, 0x79);
        theme.Badgeds.DarkBackground = BaseThemeColors.Neutral100;
        theme.Badgeds.DarkForeground = BaseThemeColors.Neutral900;
        theme.Badgeds.LightBackground = BaseThemeColors.Neutral900;
        theme.Badgeds.LightForeground = BaseThemeColors.Black900;
        theme.Buttons.FlatClick = Color.FromArgb(0x19, 0x75, 0x75, 0x75);
        theme.Buttons.Ripple = BaseThemeColors.Neutral700;
        theme.Buttons.FlatRipple = BaseThemeColors.Neutral700;
        theme.SnackBars.Ripple = BaseThemeColors.Neutral700;
        theme.SnackBars.Background = BaseThemeColors.Neutral800;
        theme.SnackBars.MouseOver = BaseThemeColors.Neutral700;
        theme.Cards.Background = BaseThemeColors.Neutral200;
        theme.Cards.Border = BaseThemeColors.Neutral500;
        theme.CheckBoxes.Disabled = BaseThemeColors.Neutral300;
        theme.CheckBoxes.UncheckedBorder = BaseThemeColors.White100;
        theme.CheckBoxes.Off = BaseThemeColors.White500;
        theme.Chips.Background = Color.FromArgb(0xFF, 0x2E, 0x3C, 0x43);
        theme.Chips.OutlineBorder = BaseThemeColors.White100;
        theme.ColorZones.DarkBackground = BaseThemeColors.Neutral100;
        theme.ColorZones.DarkForeground = BaseThemeColors.Neutral900;
        theme.ColorZones.LightBackground = BaseThemeColors.Neutral900;
        theme.ColorZones.LightForeground = BaseThemeColors.Black900;
        theme.ComboBoxes.Disabled = BaseThemeColors.Neutral300;
        theme.ComboBoxes.FilledBackground = BaseThemeColors.White100;
        theme.ComboBoxes.HoverBackground = BaseThemeColors.White100;
        theme.ComboBoxes.OutlineInactiveBorder = BaseThemeColors.White200;
        theme.ComboBoxes.HoverBorder = BaseThemeColors.White900;
        theme.ComboBoxes.Border = BaseThemeColors.White500;
        theme.ComboBoxes.OutlineBorder = BaseThemeColors.White700;
        theme.ComboBoxes.Popups.DarkBackground = BaseThemeColors.Neutral100;
        theme.ComboBoxes.Popups.DarkForeground = BaseThemeColors.Neutral900;
        theme.ComboBoxes.Popups.LightBackground = BaseThemeColors.Neutral900;
        theme.ComboBoxes.Popups.LightForeground = BaseThemeColors.Black900;
        theme.DataGrids.Border = BaseThemeColors.White100;
        theme.DataGrids.ButtonPressed = BaseThemeColors.Neutral400;
        theme.DataGrids.ComboBoxHover = BaseThemeColors.White100;
        theme.DataGrids.ComboBoxSelected = BaseThemeColors.Neutral400;
        theme.DataGrids.PopupBorder = BaseThemeColors.White100;
        theme.DataGrids.RowHoverBackground = BaseThemeColors.White100;
        theme.DataGrids.Selected = BaseThemeColors.Neutral400;
        theme.DataGrids.ColumnHeaderForeground = BaseThemeColors.White700;
        theme.TextBoxes.HoverBorder = BaseThemeColors.White900;
        theme.TextBoxes.Border = BaseThemeColors.White500;
        theme.TextBoxes.OutlineBorder = BaseThemeColors.White700;
        theme.TextBoxes.DisabledBackground = BaseThemeColors.White50;
        theme.TextBoxes.FilledBackground = BaseThemeColors.White100;
        theme.TextBoxes.HoverBackground = BaseThemeColors.White100;
        theme.TextBoxes.OutlineInactiveBorder = BaseThemeColors.White200;
        theme.PasswordBoxes.HoverBorder = BaseThemeColors.White900;
        theme.PasswordBoxes.Border = BaseThemeColors.White500;
        theme.PasswordBoxes.OutlineBorder = BaseThemeColors.White700;
        theme.PasswordBoxes.FilledBackground = BaseThemeColors.White100;
        theme.PasswordBoxes.HoverBackground = BaseThemeColors.White100;
        theme.PasswordBoxes.OutlineInactiveBorder = BaseThemeColors.White200;
        theme.GridSplitters.Background = BaseThemeColors.White100;
        theme.GridSplitters.PreviewBackground = BaseThemeColors.Neutral400;
        theme.Headers.Foreground = BaseThemeColors.White700;
        theme.ListBoxItems.Border = BaseThemeColors.White100;
        theme.ListBoxItems.Selected = BaseThemeColors.White100;
        theme.ListViews.Hover = BaseThemeColors.White100;
        theme.ListViews.Selected = BaseThemeColors.Neutral400;
        theme.ListViews.Separator = BaseThemeColors.White100;
        theme.RadioButtons.Border = BaseThemeColors.White100;
        theme.RadioButtons.Checked = BaseThemeColors.White100;
        theme.RadioButtons.Disabled = BaseThemeColors.Neutral300;
        theme.RadioButtons.Outline = BaseThemeColors.White500;
        theme.RadioButtons.Chips.CheckedBackground = BaseThemeColors.White100;
        theme.ScrollBars.ActiveBackground = BaseThemeColors.White100;
        theme.ScrollBars.Foreground = BaseThemeColors.Neutral400;
        theme.ScrollBars.RepeatButtonBackground = BaseThemeColors.Neutral400;
        theme.Separators.Background = BaseThemeColors.Neutral400;
        theme.TabControls.Divider = BaseThemeColors.White100;
        theme.ToolBars.Background = BaseThemeColors.Neutral50;
        theme.ToolBars.Separator = BaseThemeColors.White100;
        theme.ToolBars.Thumbs.Foreground = BaseThemeColors.White100;
        theme.ToolBars.Items.Background = BaseThemeColors.Neutral800;
        theme.ToolBars.Items.Foreground = BaseThemeColors.Neutral300;
        theme.ToolBars.Overflows.Border = BaseThemeColors.White100;
        theme.ToggleButtons.Background = BaseThemeColors.Neutral800;
        theme.ToggleButtons.Foreground = BaseThemeColors.Neutral300;
        theme.ToggleButtons.Switches.TrackOffBackground = BaseThemeColors.Neutral200;
        theme.ToolTips.Background = BaseThemeColors.Neutral900;
    }
}
