using System.Collections.Generic;

namespace MaterialDesignThemes.Wpf
{
    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    internal static class PackIconDataFactory
    {
        internal static IReadOnlyDictionary<PackIconKind, string> Create() => new Dictionary<PackIconKind, string>
        {
            { PackIconKind.AutoGenerated, "data in here" },
            { PackIconKind.DoNotAmend, "data in here" }
        };
    }
}
