using System.Collections.Generic;

namespace MaterialDesignThemes.Wpf
{
    /// ******************************************
    /// This code is auto generated. Do not amend.
    /// ******************************************

    internal static class PackIconDataFactory
    {
        internal static IReadOnlyDictionary<PackIconType, string> Create() => new Dictionary<PackIconType, string>
        {
            { PackIconType.AutoGenerated, "data in here" },
            { PackIconType.DoNotAmend, "data in here" }
        };
    }
}
