name: Release Published

on:
  release:
    types: [published]

defaults:
  run:
    shell: pwsh

jobs:
  publish_nugets:
    runs-on: ubuntu-latest
    name: Publish NuGets
    
    steps:
      - name: Download Release Artifacts
        run: |
          $release = (gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}) | ConvertFrom-Json
          gh release download "$($release.tag_name)" --repo "${{ github.repository }}"



